# Generated by Django 4.2.1 on 2023-05-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_url',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
