# Generated by Django 4.2.1 on 2023-05-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0004_order_payment_url_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
