# Generated by Django 4.2.1 on 2023-05-25 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0005_alter_order_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_url',
        ),
        migrations.RemoveField(
            model_name='order',
            name='token',
        ),
    ]
