# Generated by Django 4.2.1 on 2023-05-25 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='payment_api.client'),
            preserve_default=False,
        ),
    ]
